on:
  push:
    branches:
      - main-2.2

name: main - release - java 11
jobs:
  build:
    name: Releasing branch - main-2.2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        cache: 'maven'
        distribution: 'zulu'

    - name: tag - release - upload
      shell: bash
      run: ./dialob-api-build-parent/release.sh
      env:
        CI: false
        BOT_NAME: "info"
        BOT_EMAIL: "info@dialob.io"
        GITHUB_SHA: ${GITHUB_SHA}
        GITHUB_REF: ${GITHUB_REF}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        GPG_KEY_ID: ${{ secrets.DIALOB_GPG_KEY_ID }}
        GPG_KEY: ${{ secrets.DIALOB_GPG_KEY }}
        GPG_KEY_SEC:  ${{ secrets.DIALOB_GPG_SEC }}
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        
        